"""The application version must have exactly one source, and the decoder version
must be unreachable from a release bump.

These are the guards for the packaging framework itself. They fail loudly the
moment someone reintroduces a hardcoded version, which is cheaper than finding
out during a release.
"""
import re
import sys
from pathlib import Path

import pytest

import openpowerstation

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "packaging"))
sys.path.insert(0, str(ROOT / "scripts"))

import bump_version  # noqa: E402
import project_version  # noqa: E402

# Where the version string is allowed to appear as a literal. Prose in README and
# docs is exempt: it describes a release, it does not configure a build.
SOURCE_GLOBS = ["src/**/*.py", "packaging/*.py", "packaging/*.ps1", "packaging/*.spec",
                "scripts/*.py", "tests/*.py", "pyproject.toml"]
ALLOWED = {Path("src/openpowerstation/__init__.py")}


def test_single_source_matches_the_package():
    assert project_version.read() == openpowerstation.__version__


def test_version_literal_appears_in_exactly_one_place():
    """The regression this whole framework exists to prevent."""
    version = openpowerstation.__version__
    offenders = []
    for pattern in SOURCE_GLOBS:
        for path in ROOT.glob(pattern):
            relative = path.relative_to(ROOT)
            if relative in ALLOWED or not path.is_file():
                continue
            for number, line in enumerate(path.read_text("utf-8").splitlines(), 1):
                if version in line:
                    offenders.append(f"{relative}:{number}: {line.strip()}")
    assert not offenders, (
        "Hardcoded version outside src/openpowerstation/__init__.py:\n  " + "\n  ".join(offenders))


def test_pyproject_declares_a_dynamic_version():
    text = (ROOT / "pyproject.toml").read_text("utf-8")
    assert 'dynamic = ["version"]' in text
    assert 'version = {attr = "openpowerstation.__version__"}' in text
    # A static version key under [project] would silently win over the dynamic one.
    project_block = text.split("[project]", 1)[1].split("\n[", 1)[0]
    assert not re.search(r'^version\s*=', project_block, re.MULTILINE)


def test_decoder_version_is_independent_of_the_app_version():
    """A release bump must never restate what the decoder claims about the data."""
    assert openpowerstation.DECODER_VERSION == (
        "dp3-mr521/" + openpowerstation.DECODER_SCHEMA_VERSION + "+" + openpowerstation.UPSTREAM_REVISION[:12])
    source = (ROOT / "src/openpowerstation/__init__.py").read_text("utf-8")
    # The decoder string is built from its own constant, not from __version__.
    assert "__version__" not in source.split("DECODER_VERSION")[1]


def test_bumping_the_version_leaves_the_decoder_untouched(tmp_path):
    original = (ROOT / "src/openpowerstation/__init__.py").read_text("utf-8")
    copy = tmp_path / "__init__.py"
    copy.write_text(original, encoding="utf-8")
    bumped = bump_version.PATTERN.sub('__version__ = "9.9.9"', original, count=1)
    copy.write_text(bumped, encoding="utf-8")
    assert project_version.read("__version__", copy) == "9.9.9"
    assert project_version.read("DECODER_SCHEMA_VERSION", copy) == openpowerstation.DECODER_SCHEMA_VERSION


@pytest.mark.parametrize("current,level,expected", [
    ((0, 1, 2), "patch", (0, 1, 3)),
    ((0, 1, 2), "minor", (0, 2, 0)),
    ((0, 1, 2), "major", (1, 0, 0)),
    ((1, 9, 9), "minor", (1, 10, 0)),
])
def test_bump_arithmetic(current, level, expected):
    assert bump_version.bump(current, level) == expected


@pytest.mark.parametrize("argument", ["0.0.1", "nonsense", "1.2", "", "v1.2.3", "CURRENT"])
def test_bump_rejects_bad_targets(argument):
    """Never move the version backwards, sideways, or to something unparseable.

    "CURRENT" stands in for the live version so this file holds no version literal.
    """
    target = openpowerstation.__version__ if argument == "CURRENT" else argument
    assert bump_version.main([target, "--dry-run"]) == 1


def test_windows_version_resource_is_generated_from_the_source():
    version = openpowerstation.__version__
    numeric = project_version.file_version_tuple(version)
    assert numeric == tuple(int(p) for p in version.split(".")) + (0,)
    resource = ROOT / "packaging/version_info.txt"
    if resource.exists():  # Generated by prepare.py; absent in a clean checkout.
        text = resource.read_text("utf-8")
        assert f"StringStruct('FileVersion', '{version}')" in text
        assert f"StringStruct('ProductVersion', '{version}')" in text
        assert "filevers=(" + ",".join(str(n) for n in numeric) + ")" in text
    # Whether prepare.py regenerates it deterministically is tested in
    # test_packaging_prepare.py, against a copy of the tree rather than this one.
